// These are the master lists for ATS (Req #6)
export const LISTADO_PELIGROS = [
  'Atrapamiento por o entre objetos',
  'Atrapamiento por vuelco de máquinas o carga',
  'Atropello o golpe con vehículo',
  'Caídas de personas al mismo nivel',
  'Trabajo en alturas',
  'Caídas por manipulación de objetos',
  'Espacios confinados',
  'Choque contra objetos inmóviles',
  'Choque contra objetos móviles',
  'Choques de objetos desprendidos',
  'Contactos eléctricos directos',
  'Contactos eléctricos indirectos',
  'Desplome o derrumbamiento',
  'Superficies irregulares',
  'Manejo de explosivos',
  'Manejo de productos inflamables',
  'Proyección de partículas',
  'Punzamiento extremidades inferiores',
  'Inmersión en líquidos o material particulado',
  'Manejo de herramientas cortopunzantes',
  'Contactos térmicos extremos',
  'Exposición a radiación solar',
  'Exposición a temperaturas extremas',
  'Iluminación',
  'Radiación ionizante',
  'Radiación no ionizante',
  'Ruido',
  'Vibraciones',
  'Presiones anormales',
  'Exposición a aerosoles líquidos',
  'Exposición a aerosoles sólidos',
  'Exposición a gases',
  'Exposición a vapores',
  'Contaminantes biológicos',
  'Accidentes causados por animales',
  'Manipulación manual de cargas',
  'Posturas forzadas',
  'Movimientos repetitivos',
  'Incendios',
  'Sismos',
  'Explosiones',
];

export const LISTADO_MEDIDAS = [
  'Inspección del área de trabajo previo',
  'Inspección de equipos y herramientas',
  'Aplicación de Bloqueo y Etiquetado (LOTO)',
  'Señalización y delimitación del área',
  'Uso de calzado de seguridad',
  'Uso de casco',
  'Uso de EPP para ojos',
  'Uso de guantes de protección',
  'Uso de guantes con aislamiento dieléctrico',
  'Uso de arnés y línea de vida certificados',
  'Uso de protección respiratoria',
  'Uso de herramientas inspeccionadas',
  'Instalación de línea a tierra',
  'Atención al trabajo',
  'Evaluación médica previa',
  'Monitoreo de gases periódico',
  'Charla de inicio de actividades',
  'Uso de protección auditiva',
  'Uso de lámparas Explosion Proof',
  'Supervisión permanente (interno o externo)',
  'Vigía permanente para altura/confinado',
  'Guía a tierra para vehículos',
  'EPP para trabajos en caliente',
  'Armado de talud en excavaciones',
  'Uso de equipos certificados para alturas',
  'Verificación de armado de equipos de alturas',
  'Instalación e inspección de línea de vida',
  'Uso de rampas y rodajes antideslizantes',
  'Recursos permanentes de emergencia',
  'Uso de extracción y ventilación de gases',
  'Verificación de requisitos legales del personal',
  'Ingreso al área solo de personal autorizado',
  'Inspección post-tarea en área caliente',
  'Dejar enfriar maquinaria o equipos',
  'Informar en guardianía',
  'Verificación de certificaciones de equipos',
  'Comunicación permanente',
  'Personal Capacitado y entrenado',
  'Personal con inducción de HSE',
];